spring:
  profiles:
    active: dev
  application:
    name: football-club-management
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours